### ISSUE TITLE
1.21 support!

### ISSUE THREAD

**Issue by yermachello** [B1n-ry/Short-Grass#1]
Let's make some fancy pictures or renders for your mod, but in exchange you'll make a 1.21 support 😅

**Comment by peow** [comment]
a 1.20.4 support would be cool too

**Comment by B1n-ry** [comment]
I'm currently working on updating my other mod "You're in Grave Danger", but when I have some time at hand to work on this too, I will make sure it receives updates too

**Comment by B1n-ry** [comment]
The other mod is done, and now I've published version 1.3.0 for Short Grass!
It will work on all versions between 1.20.4 and 1.21
